version: '3.7'
services:
  couchdb:
    build: 
      context: ./couchdb
    container_name: couchdb
    restart: always
    environment:
      - COUCHDB_USER=username
      - COUCHDB_PASSWORD=password
      - TZ=America/Sao_Paulo
#     env_file:
#       - .env
    ports:
      - "5980:5980"
    volumes:
      - "../couch/data:/opt/couchdb/data"
    networks:
      - develop-network
  mongodb:
    build: 
      context: ./mongodb
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - TZ=America/Sao_Paulo
#     env_file:
#       - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_data:/var/www/html
    networks:
      - develop-network
  mongo-express:
      image: mongo-express
      container_name: mongoexpress
      restart: always
      environment:
          - ME_CONFIG_BASICAUTH_USERNAME=username
          - ME_CONFIG_BASICAUTH_PASSWORD=password
          - ME_CONFIG_MONGODB_PORT=27018
          - ME_CONFIG_MONGODB_ADMINUSERNAME=username
          - ME_CONFIG_MONGODB_ADMINPASSWORD=password
          - ME_CONFIG_MONGODB_SERVER=mongodb
#     env_file:
#       - .env
      links:
          - mongodb
      ports:
          - "8081:8081"
      networks:
          - fastapi-network
  postgres:
    restart: always
    build: 
      context: ./postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=50680
      - POSTGRES_ADMIN_USER=username
      - POSTGRES_ADMIN_PASSWORD=password
      - TZ=America/Sao_Paulo
#     env_file:
#       - .env
    ports:
      - "8060:8060"
    networks:
      - develop-network
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadminsec
      env_file:
          - .env
      ports:
          - "16543:80"
      depends_on:
          - postgres
      networks:
          - develop-network
  redis:
    build: 
      context: ./redis
    container_name: redis
    restart: always
    environment: 
      - TZ=America/Sao_Paulo
#     env_file:
#       - .env
    ports:
      - "6379:6379"
    networks:
      - develop-network

volumes:
  postgres_data:
  mongo_data:
    
networks:
  develop-network:
    driver: external 
