version: '3.7'

services:
    mongodb:
        container_name: container-mongodb
        build:
            dockerfile: Dockerfile
            context: ./mongodb
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=root-db
            - TZ=America/Sao_Paulo
        # env_file:
        #     - .env
        volumes:
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./mongo_data:/data/db
            - ./mongo_data:/var/www/html
        networks:
            - mongodb-network

    # mongo-express:
        # image: mongo-express:latest
        # container_name: container-mongo-express
        # restart: always
        # environment:
        #     - ME_CONFIG_OPTIONS_EDITORTHEME=default
        #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        #     - ME_CONFIG_BASICAUTH_USERNAME=admin
        #     - ME_CONFIG_BASICAUTH_PASSWORD=password
            # - ME_CONFIG_SITE_SSL_ENABLED=false
            # - ME_CONFIG_MONGODB_PORT=27017
            # - ME_CONFIG_MONGODB_SERVER=localhost
            # - ME_CONFIG_MONGODB_AUTH_USERNAME=api_user
            # - ME_CONFIG_MONGODB_AUTH_PASSWORD=api1234
            # - ME_CONFIG_MONGODB_AUTH_DATABASE=api_dev_db
        # env_file:
        #     - .env
        # volumes:
        #     - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        #     - ./mongo_data:/data/db
        #     - ./mongo_data:/var/www/html
        # links:
        #     - mongodb
        # depends_on:
        #     - mongodb
        # ports:
        #     - 8081:8081
        # networks:
        #     - mongodb-network

networks:
    mongodb-network:
        external: true

volumes:
    mongo_data:
