version: '3.7'

services:
    postgres:
        container_name: container-postgres
        build:
            dockerfile: Dockerfile
            context: ./postgres
        restart: always
        ports:
            - 15432:5432
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=root-db
            - PGDATA=/data/postgres
            - TZ=America/Sao_Paulo
        # env_file:
        #     - .env
        volumes:
            - ./postgres_data:/data/db
        networks:
            - postgres-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: container-pgadmin-postgres
        environment:
          PGADMIN_DEFAULT_EMAIL: "bruno-comitre@hotmail.com"
          PGADMIN_DEFAULT_PASSWORD: "password"
        ports:
          - "16543:80"
        depends_on:
          - postgres
        networks:
          - postgres-network

networks:
    postgres-network:
        external: true

volumes:
    postgres_data:
